# template is relative to plugin dir
template: "templates/rss.xml"
title: "Elie on Internet Security and Performance"
subtitle: "Blog about web technologies and games with a focus performance and security."
banner: /static/images/banner/fuller-house-exposing-high-end-poker-cheating-devices.jpg
icon: /static/images/favicon/favicon-160x160.png
logo_svg: /static/svg/test.svg
accent_color: 03A9F4
analytics_code: XXX
layout_type: card
url: "rss"
num_posts: 10
## The RSS content is generated directly from the markdown using
# the same parser than the normal site but with a different set of templates.
parser_config:
    # template used to format the element emitted by the parser.
    # relative to plugin directory
    template_dir: "parser_templates/"
    # choose higlights theme from https://help.farbox.com/pygments.html
    code_highlighting_theme: "monokai"
    code_display_line_num: True # display line number?